config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  get 'profiles/show'

  devise_for :users
  
  resources :posts do
  	resources :comments
  	member do
  		get 'like'
    end
    collection do
      get :vietlot
    end
  end
  
  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include SimpleHashtag::Hashtaggable
	hashtaggable_attribute :content

	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	include SimpleHashtag::Hashtaggable
	hashtaggable_attribute :title

	acts_as_votable
	
	validates :user_id, presence: true
	validates :image, presence: true
	belongs_to :user
	has_many :comments, dependent: :destroy
	
	has_attached_file :image, styles: { medium: "300x300>", :large => "500x500>" }
	crop_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_voter

    validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
    validates_uniqueness_of :user_name

    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

    has_attached_file :avatar, styles: { medium: '152x152#' }  
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :user_name
  	devise_parameter_sanitizer.for(:account_update) << :user_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post

	def index
	    @comments = @post.comments.order("created_at ASC")

	    respond_to do |format|
	      format.html { render layout: !request.xhr? }
	    end
  	end

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		else
			render root_path
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_post
		@post = Post.find(params[:post_id])
	end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
    @hashtags = SimpleHashtag::Hashtag.all
  end

  def show
    @hashtag = SimpleHashtag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
    @posts = []
    @post_ids = []
    @hashtagged.each do |hashtag|
      if hashtag.class.method_defined? :post_id
        unless @post_ids.include? hashtag.post_id
          @post_ids.push(hashtag.post_id)
          @posts.push(hashtag.post)
        end
      else
        unless @post_ids.include? hashtag.id
          @post_ids.push(hashtag.id)
          @posts.push(hashtag)
        end
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :vietlot]
	before_action :find_post, only: [:show, :edit, :update, :destroy, :like]
	before_action :owned_post, only: [:edit, :update, :destroy]
	
	def index
		@posts = Post.all.order('created_at DESC').page params[:page]
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = "Successfully created new Post!"
			redirect_to @post
		else
			flash.now[:alert] = "Create new Post failed!"
			render 'new'
		end 
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post was successfully updated!"
			redirect_to @post
		else
			flash.now[:alert] = "Update Post failed!"
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def like
		if @post.liked_by current_user
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def vietlot
		arr = []
		lucky = []

		url = 'http://vietlott.vn/vi/trung-thuong/ket-qua-trung-thuong/mega-6-45/winning-numbers/'
		page = Mechanize.new.get(url)

		days = page.search('.table-striped tbody tr')
		days.each do |day|
			numbers = day.search('td span')
			numbers.each do |number|
				arr.push(number.text)
			end
		end

		loop do
			ln = arr.sample
			lucky.push(ln) unless lucky.include? ln
			break if lucky.size == 5
		end

		render json: arr
	end

	private

	def post_params
		params.require(:post).permit(:title, :image)
	end
	
	def find_post
		@post = Post.find(params[:id])
	end

	def owned_post
		unless current_user == @post.user
			flash[:alert] = "That post doesn't belongs to you!"
    		redirect_to root_path
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_user

  def show
  	@posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
  	if @user.update(profile_params)
  		flash[:success] = 'Your profile has been updated!'
  		redirect_to profile_path(@user.user_name)
  	else
  		flash[:error] = 'Update your profile failed!'
  		render 'edit'
  	end
  end

  private

  def profile_params
  	params.require(:user).permit(:avatar, :bio)	
  end

  def find_user
  	@user = User.find_by(user_name: params[:user_name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)
		{
			success: 'alert-success',
			error: 'alert-danger',
			alert: 'alert-warning',
			notice: 'alert-info'
		}[flash_type.to_sym] || flash_type.to_s
		
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def linkify_hashtags(hashtaggable_content)
    regex = SimpleHashtag::Hashtag::HASHTAG_REGEX
    hashtagged_content = hashtaggable_content.to_s.gsub(regex) do
      link_to($&, hashtag_path($2), {class: :hashtag})
    end
    hashtagged_content.html_safe
  end

  def render_hashtaggable(hashtaggable)
    klass        = hashtaggable.class.to_s.underscore
    view_dirname = klass.pluralize
    partial      = klass
    render "#{view_dirname}/#{partial}", {klass.to_sym => hashtaggable}
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	def display_likes(post)
		votes = post.votes_for.up.by_type(User)
		return list_likers(votes) if votes.size <= 13
		count_likers(votes)
	end

	def liked_post(post)
		return 'glyphicon-heart' if current_user.voted_for? post
		'glyphicon-heart-empty'
	end

	private

	def list_likers(votes)
		user_names = []
		unless votes.blank?
			votes.voters.each do |voter|
				user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
			end
			user_names.to_sentence.html_safe + like_plural(votes)
		end
	end

	def count_likers(votes)
		vote_count = votes.size
		vote_count.to_s + 'likes'
	end

	def like_plural(votes)
		return ' like this' if votes.count > 1
		' likes this'
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.haml
%p.comment
  %b= link_to comment.user.user_name, profile_path(comment.user.user_name)
  = linkify_hashtags(comment.content)
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do
      %span.delete-comment.glyphicon.glyphicon-remove

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.haml
= render @comments, post: @post

app/views/hashtags/index.html.erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %></li>
<% end -%>
</ul>

app/views/hashtags/show.html.haml
#post_show.row
	.col-md-8.col-md-offset-2.post-top
		= render 'posts/posts'

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Instagram Clone
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		%nav.navbar.navbar-default
			.container
				.navbar-brand= link_to 'Instagram Clone', root_path
				
				%ul.nav.navbar-nav.navbar-right
					- if user_signed_in?
						%li= link_to 'New Post', new_post_path
						%li= link_to current_user.user_name, profile_path(current_user.user_name)
						%li= link_to 'Sign Out', destroy_user_session_path, method: :delete
					- else
						%li= link_to 'Sign In', new_user_session_path
						%li= link_to 'Sign Up', new_user_registration_path
						
		.container
			- flash.each do |name, msg|
				= content_tag :div, msg, class: [:alert, alert_for(name)]
				
			= yield

app/views/posts/_form.html.haml
= content_for :no_turbolink, true
= simple_form_for @post, html: { multipart: true } do |f|
	= f.error_notification
	/= f.cropbox :image
	/= f.crop_preview :image
	/= f.file_field :image
	.form-group
		= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
	.form-group.text-center
		= f.input :title, label: false, placeholder: 'Caption', input_html: { class: 'form-control' }
	.form-group.text-center
		= f.button :submit, class: 'btn btn-primary'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
	= display_likes post

app/views/posts/_post.html.haml
.panel.panel-default.post-bottom
	.panel-heading
		.user
			- if post.user.avatar.exists?
				= image_tag post.user.avatar.url(:medium)
			- else
				= image_tag 'avatar.png'
			= link_to post.user.user_name, profile_path(post.user.user_name)
		.time-ago
			= time_ago_in_words post.created_at
	.panel-body.post_image
		= link_to (image_tag post.image.url), post
	.panel-footer
		.row
			.col-md-12
				= render 'posts/likes', post: post
				%p.title
					%b= link_to post.user.user_name, profile_path(post.user.user_name)
					= linkify_hashtags(post.title)

				.comments{id: "comments_#{post.id}"}
					- if post.comments.any?
						- unless post.comments.count <= 4
							= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"}
						= render post.comments.last(4), post: post
				- if user_signed_in?
					.comment-like-form.row
						.col-sm-1
							= link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "glyphicon #{liked_post post}"		
						.comment-form.col-sm-11
							= form_for([post, post.comments.build], remote: true) do |f|
								= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"

app/views/posts/_posts.html.haml
- @posts.each do |post|
	= render 'posts/post', post: post
	

app/views/posts/crop.html.erb
<h1>Crop Image</h1>
<% content_for(:head) do %>
	<script type="text/javascript">
		$(function(){
			$("#cropbox").Jcrop();
		});
	</script>
<% end %>

<%= image_tag @post.image.url(:large), :id => 'cropbox' %>

app/views/posts/edit.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1.text-center Edit Post
			.panel-body
				.text-center 
					%strong Current Image
				%br/
				.text-center= image_tag @post.image.url(:medium), id: 'image-preview', style: 'width: 50%;'
				%br/
				= render 'form'
		.text-center
			= link_to 'Cancel', @post
			|
			= link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/index.html.haml
#post_show.row
	.col-md-8.col-md-offset-2.post-top
		= render 'posts'
#paginator.text-center
	= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/index.js.erb
$('.post-top').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }  

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1.text-center New Post
			.panel-body
				.text-center
					= image_tag 'default.jpg', id: 'image-preview', style: 'width: 50%'
				%br/
				= render 'form'

app/views/posts/show.html.haml
#post_show.row
	.col-md-8.col-md-offset-2.post-top
		= render 'post', post: @post
		- if @post.user == current_user
			.text-center
				= link_to 'Cancel', root_path
				|
				= link_to 'Edit Post', edit_post_path
		- else
			.text-center
				= link_to 'Cancel', root_path

app/views/profiles/edit.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1.text-center Update Profile
			.panel-body
				.text-center
					.post-wrapper
						.post
							.post-body
								.image-wrap
									= form_for @user, url: { action: 'update' }, html: { multipart: true } do |f|
										.row
											.col-md-12
												.form-group.text-center
													%h4 Change your avatar
													.img-circle
														- if @user.avatar.exists?
															= image_tag @user.avatar.url(:medium), id: 'image-preview'
														- else
															= image_tag 'avatar.png', id: 'image-preview'
													= f.file_field :avatar, label: false, onChange: 'loadFile(event)'
										.row
											.col-md-12
												.form-group.text-center
													%h4 Update your bio
													= f.text_area :bio, label: false, rows: 4, class: 'form-control' 
										.form-group.text-center
											= f.submit 'Update Profile', class: 'btn btn-primary'

app/views/profiles/show.html.haml
.posts-wrapper
	.row.profile-header
		.col-md-6
			.img-circle.img-show
				- if @user.avatar.exists?
					= image_tag @user.avatar.url(:medium)
				- else
					= image_tag 'avatar.png'
		.col-md-6
			.user-name-and-follow
				%h3.profile-user-name
					= @user.user_name
				%span
					- if @user == current_user
						= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button'
			%p.profile-bio
				= @user.bio
			.user-statistics
				%p
					= pluralize @user.posts.count, 'post'

#posts.transitions-enabled
	- @posts.each do |post|
		.box.panel.panel-default
			= link_to (image_tag post.image.url), post
			.panel-body
				%h2= link_to post.title, post
				%p.user
					= post.votes_for.size
					likes
				%p.user
					= post.comments.size
					comments 